/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingeolineas.vista;

/**
 *
 * @author Usuario
 */
public class FrmContratista extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmContratista
     */
    public FrmContratista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTxNombres = new javax.swing.JTextField();
        jTxApellidos = new javax.swing.JTextField();
        jTxCargo = new javax.swing.JTextField();
        jTxDireccion = new javax.swing.JTextField();
        jTxTelefono = new javax.swing.JTextField();
        jTxCiudad = new javax.swing.JTextField();
        jTxCedula = new javax.swing.JTextField();
        jTxCodigoProyecto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLbCargo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCbCodigoProyecto = new javax.swing.JComboBox<>();
        jBtNuevo = new javax.swing.JButton();
        jBtGuardar = new javax.swing.JButton();
        jBtModificar = new javax.swing.JButton();
        jBtEliminar = new javax.swing.JButton();
        jBtConsultar = new javax.swing.JButton();
        jBtSalir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jTxNombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxNombresActionPerformed(evt);
            }
        });

        jTxApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxApellidosActionPerformed(evt);
            }
        });

        jTxCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTxDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTxTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTxCiudad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTxCedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxCedulaActionPerformed(evt);
            }
        });

        jTxCodigoProyecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxCodigoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxCodigoProyectoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombres");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Apellidos");

        jLbCargo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbCargo.setText("Cargo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Dirección");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Teléfono");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ciudad");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Id Cédula");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Código Proyecto");

        jBtNuevo.setBackground(new java.awt.Color(0, 204, 153));
        jBtNuevo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtNuevo.setText("Nuevo");

        jBtGuardar.setBackground(new java.awt.Color(0, 204, 153));
        jBtGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtGuardar.setText("Guardar");

        jBtModificar.setBackground(new java.awt.Color(0, 204, 153));
        jBtModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtModificar.setText("Modificar");

        jBtEliminar.setBackground(new java.awt.Color(0, 204, 153));
        jBtEliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtEliminar.setText("Eliminar");

        jBtConsultar.setBackground(new java.awt.Color(0, 204, 153));
        jBtConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtConsultar.setText("Consultar");

        jBtSalir.setBackground(new java.awt.Color(0, 204, 153));
        jBtSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtSalir.setText("Salir");

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel11.setText("Contratista");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ingeolineas S.A.S");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jCbCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(208, 208, 208))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addGap(55, 55, 55)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxNombres)
                                        .addComponent(jTxCedula)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 121, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(159, 159, 159)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jBtNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jBtGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addComponent(jLabel11))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCbCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtNuevo)
                    .addComponent(jBtGuardar)
                    .addComponent(jBtModificar)
                    .addComponent(jBtEliminar)
                    .addComponent(jBtConsultar)
                    .addComponent(jBtSalir))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxCedulaActionPerformed

    private void jTxNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxNombresActionPerformed

    private void jTxApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxApellidosActionPerformed

    private void jTxCodigoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxCodigoProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxCodigoProyectoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtConsultar;
    public javax.swing.JButton jBtEliminar;
    public javax.swing.JButton jBtGuardar;
    public javax.swing.JButton jBtModificar;
    public javax.swing.JButton jBtNuevo;
    public javax.swing.JButton jBtSalir;
    public javax.swing.JComboBox<String> jCbCodigoProyecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLbCargo;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTxApellidos;
    public javax.swing.JTextField jTxCargo;
    public javax.swing.JTextField jTxCedula;
    public javax.swing.JTextField jTxCiudad;
    public javax.swing.JTextField jTxCodigoProyecto;
    public javax.swing.JTextField jTxDireccion;
    public javax.swing.JTextField jTxNombres;
    public javax.swing.JTextField jTxTelefono;
    // End of variables declaration//GEN-END:variables
}
