/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingeolineas.vista;

/**
 *
 * @author braya
 */
public class FrmDocumentoSgsst extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDocumentoSgsst
     */
    public FrmDocumentoSgsst() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtEliminar = new javax.swing.JButton();
        jBtGuardar = new javax.swing.JButton();
        jBtModificar = new javax.swing.JButton();
        jBtNuevo = new javax.swing.JButton();
        jBtConsultar = new javax.swing.JButton();
        jBtSalir = new javax.swing.JButton();
        jTxNombreDocumento = new javax.swing.JTextField();
        jTxCodigosg = new javax.swing.JTextField();
        jCbCodigoProyecto = new javax.swing.JComboBox<>();
        jTxCodigoProyecto = new javax.swing.JTextField();
        jLbCodigoProyecto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Código SG");

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setText("Codigo SG");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre Documento");

        jBtEliminar.setBackground(new java.awt.Color(0, 204, 153));
        jBtEliminar.setText("Eliminar");

        jBtGuardar.setBackground(new java.awt.Color(0, 204, 153));
        jBtGuardar.setText("Guardar");

        jBtModificar.setBackground(new java.awt.Color(0, 204, 153));
        jBtModificar.setText("Modificar");

        jBtNuevo.setBackground(new java.awt.Color(0, 204, 153));
        jBtNuevo.setText("Nuevo");
        jBtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNuevoActionPerformed(evt);
            }
        });

        jBtConsultar.setBackground(new java.awt.Color(0, 204, 153));
        jBtConsultar.setText("Consultar");

        jBtSalir.setBackground(new java.awt.Color(0, 204, 153));
        jBtSalir.setText("Salir");

        jTxNombreDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxNombreDocumentoActionPerformed(evt);
            }
        });

        jTxCodigosg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxCodigosgActionPerformed(evt);
            }
        });

        jTxCodigoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxCodigoProyectoActionPerformed(evt);
            }
        });

        jLbCodigoProyecto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLbCodigoProyecto.setText("Código Proyecto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Ingeolineas S.A.S");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jBtNuevo)
                .addGap(18, 18, 18)
                .addComponent(jBtGuardar)
                .addGap(18, 18, 18)
                .addComponent(jBtModificar)
                .addGap(18, 18, 18)
                .addComponent(jBtEliminar)
                .addGap(18, 18, 18)
                .addComponent(jBtConsultar)
                .addGap(18, 18, 18)
                .addComponent(jBtSalir)
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLbCodigoProyecto))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxCodigosg, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(jTxNombreDocumento))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCbCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxNombreDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxCodigosg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxCodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbCodigoProyecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtEliminar)
                    .addComponent(jBtGuardar)
                    .addComponent(jBtModificar)
                    .addComponent(jBtNuevo)
                    .addComponent(jBtConsultar)
                    .addComponent(jBtSalir))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtNuevoActionPerformed

    private void jTxNombreDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxNombreDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxNombreDocumentoActionPerformed

    private void jTxCodigosgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxCodigosgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxCodigosgActionPerformed

    private void jTxCodigoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxCodigoProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxCodigoProyectoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtConsultar;
    public javax.swing.JButton jBtEliminar;
    public javax.swing.JButton jBtGuardar;
    public javax.swing.JButton jBtModificar;
    public javax.swing.JButton jBtNuevo;
    public javax.swing.JButton jBtSalir;
    public javax.swing.JComboBox<String> jCbCodigoProyecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLbCodigoProyecto;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTxCodigoProyecto;
    public javax.swing.JTextField jTxCodigosg;
    public javax.swing.JTextField jTxNombreDocumento;
    // End of variables declaration//GEN-END:variables
}
