/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingeolineas.vista;

import ingeolineas.controlador.ControladorContratista;
import ingeolineas.controlador.ControladorDocumentoSgsst;
import ingeolineas.controlador.ControladorElementoPp;
import ingeolineas.controlador.ControladorProyecto;
import ingeolineas.modelo.Contratista;
import ingeolineas.modelo.ContratistaDAO;
import ingeolineas.modelo.DocumentoSgsst;
import ingeolineas.modelo.DocumentoSgsstDAO;
import ingeolineas.modelo.ElementoPp;
import ingeolineas.modelo.ElementoPpDAO;
import ingeolineas.modelo.Proyecto;
import ingeolineas.modelo.ProyectoDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMiContratista = new javax.swing.JMenuItem();
        jMiProyecto = new javax.swing.JMenuItem();
        jMiDocumentoSG = new javax.swing.JMenuItem();
        jMiElementosPP = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Menú");

        jMiContratista.setText("Contratista");
        jMiContratista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiContratistaActionPerformed(evt);
            }
        });
        jMenu1.add(jMiContratista);

        jMiProyecto.setText("Proyecto");
        jMiProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiProyectoActionPerformed(evt);
            }
        });
        jMenu1.add(jMiProyecto);

        jMiDocumentoSG.setText("Documentos SG-SST");
        jMiDocumentoSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiDocumentoSGActionPerformed(evt);
            }
        });
        jMenu1.add(jMiDocumentoSG);

        jMiElementosPP.setText("Elementos de Protección Personal");
        jMiElementosPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiElementosPPActionPerformed(evt);
            }
        });
        jMenu1.add(jMiElementosPP);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaccional");

        jMenuItem3.setText("Contratos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consultas");

        jMenuItem8.setText("Consultar Proyecto");
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Consultar EPP");
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMiContratistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiContratistaActionPerformed
        Contratista contra = new Contratista();
        ContratistaDAO contraD = new ContratistaDAO();
       FrmContratista fcontra = new FrmContratista();
        try {
        ControladorContratista contraC = new ControladorContratista(fcontra, contra, contraD);
        } catch (SQLException ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
       jDesktopPane1.add(fcontra);
       fcontra.show();
    }//GEN-LAST:event_jMiContratistaActionPerformed

    private void jMiProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiProyectoActionPerformed
        Proyecto proyec = new Proyecto();
        ProyectoDAO proyecD = new ProyectoDAO();
        FrmProyecto fproyecto = new FrmProyecto();
        ControladorProyecto proyecC = new ControladorProyecto(fproyecto, proyec, proyecD);
        jDesktopPane1.add(fproyecto);
        fproyecto.show();
    }//GEN-LAST:event_jMiProyectoActionPerformed

    private void jMiElementosPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiElementosPPActionPerformed
        ElementoPp elemento = new ElementoPp();
        ElementoPpDAO elementoD = new ElementoPpDAO();
        FrmElementoPp felemento = new FrmElementoPp();
        try {
            ControladorElementoPp elementoC = new ControladorElementoPp(felemento, elemento, elementoD);
        } catch (SQLException ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        } 
       jDesktopPane1.add(felemento);
       felemento.show();
    }//GEN-LAST:event_jMiElementosPPActionPerformed

    private void jMiDocumentoSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiDocumentoSGActionPerformed
        DocumentoSgsst document = new DocumentoSgsst();
        DocumentoSgsstDAO documentD = new DocumentoSgsstDAO();
        FrmDocumentoSgsst fdocument = new FrmDocumentoSgsst();
        try {
            ControladorDocumentoSgsst contraC = new ControladorDocumentoSgsst(fdocument, document, documentD);
        } catch (SQLException ex) {
            Logger.getLogger(FrmMenu.class.getName()).log(Level.SEVERE, null, ex);
        } 
       jDesktopPane1.add(fdocument);
       fdocument.show();
           
    }//GEN-LAST:event_jMiDocumentoSGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMiContratista;
    private javax.swing.JMenuItem jMiDocumentoSG;
    private javax.swing.JMenuItem jMiElementosPP;
    private javax.swing.JMenuItem jMiProyecto;
    // End of variables declaration//GEN-END:variables
}
