/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingeolineas.vista;

import ingeolineas.controlador.ControladorValidacion;
import ingeolineas.modelo.Usuario;
import ingeolineas.modelo.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form FrmUsuarios
     */
    public FrmUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        validar();
    }
    public void validar() {
       if(jTxIdUsuario.getText().isEmpty()) {
            jLbIdUsuario.setText("*Campo Id Usuario requerido");

        }else if(jTxIdUsuario.getText().length() > 10) {
            jLbIdUsuario.setText("*Máximo 10 caracteres");
        }else{
            jLbIdUsuario.setText("");
        }
       
       if(jTxNombreUsuario.getText().isEmpty()) {
            jLbNomUsuario.setText("*Campo Nombre Usuario requerido");
        }else if(jTxNombreUsuario.getText().length() > 40) {
            jLbNomUsuario.setText("*Máximo 40 caracteres");
        }else{
            jLbNomUsuario.setText("");
        }
       
       if(jTxUsuario.getText().isEmpty()) {
            jLbUsuario.setText("*Campo Usuario requerido");

        }else if(jTxUsuario.getText().length() > 10) {
            jLbUsuario.setText("*Máximo 10 caracteres");
        }else{
            jLbUsuario.setText("");
        }
       
        if(jPsContrasenia.getText().isEmpty()) {
            jLbContrasenia.setText("*Campo Contraseña requerido");
        }else if(jPsContrasenia.getText().length() > 10) {
            jLbContrasenia.setText("*Máximo 10 caracteres");
        }else{
            jLbContrasenia.setText("");
        }
        
         if(jTxCorreo.getText().isEmpty()) {
            jLbCorreo.setText("*Campo Correo requerido");
        }else if(jTxCorreo.getText().length() > 40) {
            jLbCorreo.setText("*Máximo 40 caracteres");
        }else{
            jLbCorreo.setText("");
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBtRegistrarse = new javax.swing.JButton();
        jTxIdUsuario = new javax.swing.JTextField();
        jTxNombreUsuario = new javax.swing.JTextField();
        jTxUsuario = new javax.swing.JTextField();
        jTxCorreo = new javax.swing.JTextField();
        jPsContrasenia = new javax.swing.JPasswordField();
        jLbIdUsuario = new javax.swing.JLabel();
        jLbNomUsuario = new javax.swing.JLabel();
        jLbUsuario = new javax.swing.JLabel();
        jLbContrasenia = new javax.swing.JLabel();
        jLbCorreo = new javax.swing.JLabel();
        jBtCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Id Usuario");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre Usuario");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Contraseña");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Correo");

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel6.setText("Registro de nuevo Usuario");

        jBtRegistrarse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtRegistrarse.setText("Registrarse");
        jBtRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRegistrarseActionPerformed(evt);
            }
        });

        jTxIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxIdUsuarioActionPerformed(evt);
            }
        });
        jTxIdUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxIdUsuarioKeyReleased(evt);
            }
        });

        jTxNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxNombreUsuarioActionPerformed(evt);
            }
        });
        jTxNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxNombreUsuarioKeyReleased(evt);
            }
        });

        jTxUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxUsuarioActionPerformed(evt);
            }
        });
        jTxUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxUsuarioKeyReleased(evt);
            }
        });

        jTxCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxCorreoActionPerformed(evt);
            }
        });
        jTxCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxCorreoKeyReleased(evt);
            }
        });

        jPsContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPsContraseniaActionPerformed(evt);
            }
        });
        jPsContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPsContraseniaKeyReleased(evt);
            }
        });

        jLbIdUsuario.setForeground(new java.awt.Color(255, 51, 51));
        jLbIdUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLbIdUsuarioKeyReleased(evt);
            }
        });

        jLbNomUsuario.setForeground(new java.awt.Color(255, 51, 51));
        jLbNomUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLbNomUsuarioKeyReleased(evt);
            }
        });

        jLbUsuario.setForeground(new java.awt.Color(255, 51, 51));
        jLbUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLbUsuarioKeyReleased(evt);
            }
        });

        jLbContrasenia.setForeground(new java.awt.Color(255, 51, 51));
        jLbContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLbContraseniaKeyReleased(evt);
            }
        });

        jLbCorreo.setForeground(new java.awt.Color(255, 51, 51));
        jLbCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLbCorreoKeyReleased(evt);
            }
        });

        jBtCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtCancelar.setText("Cancelar");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Ingeolineas S.A.S");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLbCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLbIdUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTxIdUsuario)
                                    .addComponent(jTxNombreUsuario)
                                    .addComponent(jLbNomUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLbContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPsContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                    .addComponent(jTxUsuario)
                                    .addComponent(jTxCorreo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtRegistrarse)
                                .addGap(34, 34, 34)
                                .addComponent(jBtCancelar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel6)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPsContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTxCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtRegistrarse)
                    .addComponent(jBtCancelar))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxIdUsuarioActionPerformed
       
    }//GEN-LAST:event_jTxIdUsuarioActionPerformed

    private void jTxNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxNombreUsuarioActionPerformed
        
    }//GEN-LAST:event_jTxNombreUsuarioActionPerformed

    private void jTxCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxCorreoActionPerformed

    private void jPsContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPsContraseniaActionPerformed
       
    }//GEN-LAST:event_jPsContraseniaActionPerformed

    private void jTxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxUsuarioActionPerformed

    private void jLbIdUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLbIdUsuarioKeyReleased
        
    }//GEN-LAST:event_jLbIdUsuarioKeyReleased

    private void jLbNomUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLbNomUsuarioKeyReleased
        
    }//GEN-LAST:event_jLbNomUsuarioKeyReleased

    private void jLbUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLbUsuarioKeyReleased
       
    }//GEN-LAST:event_jLbUsuarioKeyReleased

    private void jLbContraseniaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLbContraseniaKeyReleased
        
    }//GEN-LAST:event_jLbContraseniaKeyReleased

    private void jLbCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLbCorreoKeyReleased
       
    }//GEN-LAST:event_jLbCorreoKeyReleased

    private void jTxIdUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxIdUsuarioKeyReleased
         validar();
    }//GEN-LAST:event_jTxIdUsuarioKeyReleased

    private void jTxNombreUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxNombreUsuarioKeyReleased
         validar();
    }//GEN-LAST:event_jTxNombreUsuarioKeyReleased

    private void jTxUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxUsuarioKeyReleased
         validar();
    }//GEN-LAST:event_jTxUsuarioKeyReleased

    private void jPsContraseniaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPsContraseniaKeyReleased
         validar();
    }//GEN-LAST:event_jPsContraseniaKeyReleased

    private void jTxCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxCorreoKeyReleased
         validar();
    }//GEN-LAST:event_jTxCorreoKeyReleased

    private void jBtRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRegistrarseActionPerformed
        Usuario user= new Usuario();
        UsuarioDAO userD = new UsuarioDAO();
        FrmValidacion fvalida = new FrmValidacion();
        ControladorValidacion contravalida = new ControladorValidacion(fvalida,userD,user);
        fvalida.setVisible(true);
        this.dispose();
        
        /*FrmValidacion verFormularioValidacion = new FrmValidacion();
        verFormularioValidacion.setVisible(true);
        this.dispose();*/
        
        
         
    }//GEN-LAST:event_jBtRegistrarseActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
       Usuario user= new Usuario();
        UsuarioDAO userD = new UsuarioDAO();
        FrmValidacion fvalida = new FrmValidacion();
        ControladorValidacion contravalida = new ControladorValidacion(fvalida,userD,user);
        fvalida.setVisible(true);
        
        int respuesta = JOptionPane.showConfirmDialog(this,"¿Está seguro que desea cancelar?", "Fin productos", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == JOptionPane.YES_OPTION) {
                this.dispose();
            }
    }//GEN-LAST:event_jBtCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtCancelar;
    public javax.swing.JButton jBtRegistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLbContrasenia;
    public javax.swing.JLabel jLbCorreo;
    public javax.swing.JLabel jLbIdUsuario;
    public javax.swing.JLabel jLbNomUsuario;
    public javax.swing.JLabel jLbUsuario;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField jPsContrasenia;
    public javax.swing.JTextField jTxCorreo;
    public javax.swing.JTextField jTxIdUsuario;
    public javax.swing.JTextField jTxNombreUsuario;
    public javax.swing.JTextField jTxUsuario;
    // End of variables declaration//GEN-END:variables
}
